//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VY1
{
    using System;
    using System.Collections.Generic;
    
    public partial class LinjeStasjons
    {
        public int Id { get; set; }
        public Nullable<int> Linje_Id { get; set; }
        public Nullable<int> Stasjon_Id { get; set; }
    
        public virtual Linjes Linjes { get; set; }
        public virtual Stasjons Stasjons { get; set; }
    }
}
